### ISSUE TITLE
直接断掉apollo config 进程，node就hung住了

### ISSUE THREAD

**Issue by ztyandjw** [shinux/node-apollo-client#1]
直接断掉apollo config 进程，node就hung住了

init

const Apollo = require('node-apollo-client')
const apollo = new Apollo({
	configServerUrl: 'http://10.100.100.20:8080',
	appId: '001',
	cluster: 'default', // default to `default`
	namespaces: ['application'],  // default to `['application']`, this is the namespaces that you want to use or maintain.
	// initialConfigs: {
	//   application: {  // this is default namespace name
	// 	foo: 'Mars',
	// 	bar: 'Jupiter'
	//   },
	// }, // optional
	listenOnNotification: true, // default to true
	fetchCacheInterval: 5 * 60e3, // default to 5 minutes. can be customize but 30s or shorter time are not acceptable.
	cachedConfigFilePath: '/tmpp' // default to '/tmp/', cached configs path.
  });

use:

apollo.fetchConfigs({ keys: [ 'DEBUG', 'ALLOWED_HOSTS' ] }).then(data => console.log(data['DEBUG']));

**Comment by shinux** [comment]
Apollo 服务断开，node-apollo-client 实例化的对象内部的各类请求应该会持续失败，但是有重试间隔，这个不应该导致整个脚本不可用。

给一些内部请求增加了 try cach 不要再抛给外部调用者 https://github.com/shinux/node-apollo-client/commit/6809252e2e9d891390b2bc489f6ec58ad9a5cbc8

可以重新 install 一下最近版本的 package，或者提供更多的信息和使用场景的描述？

**Comment by shinux** [comment]
https://github.com/shinux/node-apollo-client/commit/8a25423f7b904fbca16d8206b4072792bb819026
修正了可能导致栈溢出的订阅递归
