### ISSUE TITLE
Error TS2497

### ISSUE THREAD

**Issue by chf007** [shinux/node-apollo-client#4]
Nest 6.8 下使用 node-apollo-client 报这个错。

`TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.`

我的 "typescript": "~3.5.3",

我的tsconfig
`
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@env-kc-web-bff/environment": ["apps/kc-web-bff/src/environments/environment.ts"],
      "@kc-web-bff/shared-nest": ["libs/shared-nest/src/index.ts"],
      "@kc-web-bff/big-data-api": ["libs/big-data-api/src/index.ts"],
      "@kc-web-bff/java-kc-api": ["libs/java-kc-api/src/index.ts"]
    }
  },
  "exclude": ["node_modules", "tmp"]
}

`

**Comment by shinux** [comment]
不好意思，code 是在 node 8 下开发并保证可用性的，比较重要的改动和区别就是 package 的引入语法等。
旧语言版本，还请自己做一下修改🙏🙏

![image](https://user-images.githubusercontent.com/7784713/71797830-b8aa2580-308a-11ea-85a9-86d888b9fff6.png)

**Comment by chf007** [comment]
所以我 fork 出来一份，只能自已改了 

> 不好意思，code 是在 node 8 下开发�并保证可用性的，比较重要的改动和区别就是 package 的引入语法等。
> 旧语言版本，还请自己做一下修改🙏🙏
> 
> ![image](https://user-images.githubusercontent.com/7784713/71797830-b8aa2580-308a-11ea-85a9-86d888b9fff6.png)
